__include__: [./synthetic_exp_020_anrep1_offset_per.yml]

output_dir: ./outputs/synthetic_exp_020_loss_prob_angle_kld
epoches: 80

DEIMCriterion:
  weight_dict:
    loss_mal: 1
    loss_bbox: 5
    loss_probiou: 5
    loss_angle: 3
    loss_kld: 2
    loss_fgl: 0.15
    loss_ddf: 1.5
  use_yolo_probiou: true
  use_yolo_angle: true
  keep_kld: true
  angle_lambda: 3.0
  matcher:
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_probiou: 5, cost_angle: 3, cost_chamfer: 2, late_cost_bbox: 0.25}
    angle_order_alpha: 1.0
