print_freq: 500
output_dir: ./outputs/synthetic_exp_decouple_020
checkpoint_freq: 10
sync_bn: true
find_unused_parameters: true
use_amp: true
scaler:
  type: GradScaler
  enabled: true
use_ema: true
ema:
  type: ModelEMA
  decay: 0.9998
  warmups: 500
  start: 0
train_dataloader:
  dataset:
    transforms:
      ops:
      - type: Mosaic
        output_size: 128
        rotation_range: 10
        translation_range:
        - 0.1
        - 0.1
        scaling_range:
        - 0.5
        - 1.5
        probability: 1.0
        fill_value: 0
        use_cache: true
        max_cached_images: 30
        random_pop: true
      - type: RandomPhotometricDistort
        p: 0.5
      - type: OBBZoomOut
        fill: 0
      - type: OBBIoUCrop
        p: 0.8
      - type: OBBSanitize
        min_size: 1
      - type: OBBFlip
      - type: OBBResize
        size:
        - 256
        - 256
      - type: OBBSanitize
        min_size: 1
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: OBBConvertBoxes
        normalize: true
        img_size:
        - 256
        - 256
      - type: Normalize
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
      policy:
        name: stop_epoch
        epoch:
        - 4
        - 29
        - 50
        ops:
        - Mosaic
        - RandomPhotometricDistort
        - OBBZoomOut
        - OBBIoUCrop
      type: Compose
      mosaic_prob: 0.5
    type: DotaDataset
    img_folder: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/density_020/train
    ann_folder: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/density_020/train
    classes_file: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/classes.txt
    format: DOTA
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 256
    base_size_repeat: 4
    stop_epoch: 50
    mixup_prob: 0.5
    mixup_epochs:
    - 4
    - 29
    copyblend_prob: 0.5
    copyblend_epochs:
    - 4
    - 50
    area_threshold: 100
    num_objects: 3
    with_expand: true
    expand_ratios:
    - 0.1
    - 0.25
    ema_restart_decay: 0.9999
  shuffle: true
  total_batch_size: 12
  num_workers: 2
  type: DataLoader
  drop_last: true
val_dataloader:
  dataset:
    transforms:
      ops:
      - type: OBBResize
        size:
        - 256
        - 256
      - type: ConvertPILImage
        dtype: float32
        scale: true
      - type: OBBConvertBoxes
        normalize: true
        img_size:
        - 256
        - 256
      - type: Normalize
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
      type: Compose
    type: DotaDataset
    img_folder: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/density_020/val
    ann_folder: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/density_020/val
    classes_file: /mnt/d/project_data/model_test/deimv2_obb_train_data/synthetic_ellipse/classes.txt
    format: DOTA
  shuffle: true
  total_batch_size: 8
  num_workers: 2
  type: DataLoader
  drop_last: true
  collate_fn:
    type: BatchImageCollateFunction
epoches: 30
clip_max_norm: 0.1
optimizer:
  type: AdamW
  params:
  - params: ^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$
    lr: 1.0e-05
  - params: ^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$
    lr: 1.0e-05
    weight_decay: 0.0
  - params: ^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$
    weight_decay: 0.0
  lr: 0.0005
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.000125
lr_scheduler:
  type: MultiStepLR
  milestones:
  - 500
  gamma: 0.1
lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 250
task: detection
num_classes: 3
model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor
use_focal_loss: true
eval_spatial_size:
- 256
- 256
DEIM:
  backbone: DINOv3STAsResAtten
  encoder: HybridEncoder
  decoder: DEIMTransformer
HGNetv2:
  name: B4
  return_idx:
  - 1
  - 2
  - 3
  freeze_at: -1
  freeze_stem_only: true
  freeze_norm: false
  pretrained: true
  local_model_dir: ./weight/hgnetv2/
HybridEncoder:
  in_channels:
  - 256
  - 256
  - 256
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  use_encoder_idx:
  - 2
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: gelu
  expansion: 1.25
  depth_mult: 1.37
  act: silu
  version: deim
  csp_type: csp2
  fuse_op: sum
DEIMTransformer:
  feat_channels:
  - 256
  - 256
  - 256
  feat_strides:
  - 8
  - 16
  - 32
  hidden_dim: 256
  num_levels: 3
  num_layers: 6
  eval_idx: -1
  num_queries: 300
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 0.5
  reg_max: 32
  reg_scale: 4
  layer_scale: 1
  num_points:
  - 3
  - 6
  - 3
  cross_attn_method: default
  query_select_method: default
  activation: silu
  mlp_act: silu
  dim_feedforward: 2048
  box_mode: obb
  decouple_angle: True
  angle_step: 10
  num_r_layers: 6
PostProcessor:
  num_top_queries: 300
  box_mode: obb
lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 5
flat_epoch: 18
no_aug_epoch: 3
DEIMCriterion:
  weight_dict:
    loss_mal: 4
    loss_bbox: 1
    loss_giou: 2
    loss_fgl: 0.5
    loss_ddf: 1.5
    loss_kld: 1
  losses:
  - mal
  - boxes
  - local
  gamma: 1.5
  alpha: 0.75
  reg_max: 32
  matcher:
    type: HungarianMatcher
    weight_dict:
      cost_class: 2
      cost_bbox: 5
      cost_giou: 2
      cost_chamfer: 5
      cost_probiou: 2
    alpha: 0.25
    gamma: 2.0
    change_matcher: true
    iou_order_alpha: 4.0
    # 0.75~0.85 * epoches
    matcher_change_epoch: 22
    box_mode: obb
  box_mode: obb
  mal_iou_type: giou
  local_iou_type: giou
comet_project_name: deimv2_obb_synthetic
DINOv3STAs:
  name: dinov3_vits16plus
  weights_path: ./ckpts/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  interaction_indexes:
  - 5
  - 8
  - 11
  finetune: true
  conv_inplane: 64
  hidden_dim: 256
DINOv3STAsResAtten:
  name: dinov3_vits16plus
  weights_path: /home/cx/win_dir/thired/DEIMv2_DAOD/ckpts/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  interaction_indexes: []
  finetune: false
  conv_inplane: 64
  hidden_dim: 256
  adapter_type: sta
KendallWeighting:
  enabled: true
  sigma_lr: 0.001
  init_log_sigma: 0.0
