DEIMV2_X_CFG = {
    "DINOv3STAsResAtten": {
        "name": "dinov3_vits16plus",
        "weights_path": "",
        "embed_dim": 256,
        "interaction_indexes": [5, 8, 11],
        "num_heads": None,
        "conv_inplane": 64,
        "hidden_dim": 256,
        "adapter_type": "sta",
    },
    "HybridEncoder": {
        "in_channels": [256, 256, 256],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 256,
        "use_encoder_idx": [2],
        "num_encoder_layers": 1,
        "nhead": 8,
        "dim_feedforward": 1024,
        "dropout": 0.0,
        "enc_act": "gelu",
        "expansion": 1.25,
        "depth_mult": 1.37,
        "act": "silu",
        "version": "deim",
        "csp_type": "csp2",
        "fuse_op": "sum",
    },
    "DEIMTransformer": {
        "num_classes": "",
        "feat_channels": [256, 256, 256],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 256,
        "num_levels": 3,
        "num_layers": 6,
        "eval_idx": -1,
        "num_queries": 300,
        "num_denoising": 100,
        "label_noise_ratio": 0.5,
        "box_noise_scale": 1.0,
        "reg_max": 32,
        "reg_scale": 4,
        "layer_scale": 1,
        "num_points": [3, 6, 3],
        "cross_attn_method": "default",
        "query_select_method": "default",
        "activation": "silu",
        "mlp_act": "silu",
        "dim_feedforward": 2048,
        "eval_spatial_size": [640, 640],
    },
    "PostProcessor": {"num_classes": "", "num_top_queries": 50},
}

DEIMV2_B_CFG = {
    "DINOv3STAs": {
        "name": "dinov3_vitb16",
        "weights_path": "",
        "embed_dim": 768,
        "interaction_indexes": [5, 8, 11],
        "num_heads": 12,
        "conv_inplane": 128,
        "hidden_dim": 512,
    },
    "HybridEncoder": {
        "in_channels": [512, 512, 512],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 512,
        "use_encoder_idx": [2],
        "num_encoder_layers": 1,
        "nhead": 8,
        "dim_feedforward": 2048,
        "dropout": 0.0,
        "enc_act": "gelu",
        "expansion": 1.25,
        "depth_mult": 1.37,
        "act": "silu",
        "version": "deim",
        "csp_type": "csp2",
        "fuse_op": "sum",
    },
    "DEIMTransformer": {
        "num_classes": "",
        "feat_channels": [512, 512, 512],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 512,
        "num_levels": 3,
        "num_layers": 6,
        "eval_idx": -1,
        "num_queries": 300,
        "num_denoising": 100,
        "label_noise_ratio": 0.5,
        "box_noise_scale": 1.0,
        "reg_max": 32,
        "reg_scale": 4,
        "layer_scale": 1,
        "num_points": [3, 6, 3],
        "cross_attn_method": "default",
        "query_select_method": "default",
        "activation": "silu",
        "mlp_act": "silu",
        "dim_feedforward": 4096,
        "eval_spatial_size": [640, 640],
    },
    "PostProcessor": {"num_classes": "", "num_top_queries": 50},
}


DEIMV2_VITL16P_CFG = {
    "DINOv3STAsResAtten": {
        "name": "dinov3_vitl16",
        "weights_path": "",
        "embed_dim": 1024,
        "interaction_indexes": [],
        "num_heads": 16,
        "conv_inplane": 128,
        "hidden_dim": 512,
        "adapter_type": "sta",
    },
    "HybridEncoder": {
        "in_channels": [512, 512, 512],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 512,
        "use_encoder_idx": [2],
        "num_encoder_layers": 1,
        "nhead": 8,
        "dim_feedforward": 2048,
        "dropout": 0.0,
        "enc_act": "gelu",
        "expansion": 1.25,
        "depth_mult": 1.37,
        "act": "silu",
        "version": "deim",
        "csp_type": "csp2",
        "fuse_op": "sum",
    },
    "DEIMTransformer": {
        "num_classes": "",
        "feat_channels": [512, 512, 512],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 512,
        "num_levels": 3,
        "num_layers": 6,
        "eval_idx": -1,
        "num_queries": 300,
        "num_denoising": 100,
        "label_noise_ratio": 0.5,
        "box_noise_scale": 1.0,
        "reg_max": 32,
        "reg_scale": 4,
        "layer_scale": 1,
        "num_points": [3, 6, 3],
        "cross_attn_method": "default",
        "query_select_method": "default",
        "activation": "silu",
        "mlp_act": "silu",
        "dim_feedforward": 4096,
        "eval_spatial_size": [640, 640],
    },
    "PostProcessor": {"num_classes": 3, "num_top_queries": 50},
}

DEIMV2_VITH16P_CFG = {
    "DINOv3STAsResAtten": {
        "name": "dinov3_vith16plus",
        "weights_path": "",
        "embed_dim": 1280,
        "interaction_indexes": [],
        "num_heads": 20,
        "conv_inplane": 160,
        "hidden_dim": 640,
        "adapter_type": "sta",
    },
    "HybridEncoder": {
        "in_channels": [640, 640, 640],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 640,
        "use_encoder_idx": [2],
        "num_encoder_layers": 1,
        "nhead": 8,
        "dim_feedforward": 2560,
        "dropout": 0.0,
        "enc_act": "gelu",
        "expansion": 1.25,
        "depth_mult": 1.37,
        "act": "silu",
        "version": "deim",
        "csp_type": "csp2",
        "fuse_op": "sum",
    },
    "DEIMTransformer": {
        "num_classes": "",
        "feat_channels": [640, 640, 640],
        "feat_strides": [8, 16, 32],
        "hidden_dim": 640,
        "num_levels": 3,
        "num_layers": 6,
        "eval_idx": -1,
        "num_queries": 300,
        "num_denoising": 100,
        "label_noise_ratio": 0.5,
        "box_noise_scale": 1.0,
        "reg_max": 32,
        "reg_scale": 4,
        "layer_scale": 1,
        "num_points": [3, 6, 3],
        "cross_attn_method": "default",
        "query_select_method": "default",
        "activation": "silu",
        "mlp_act": "silu",
        "dim_feedforward": 2560,
        "eval_spatial_size": [640, 640],
    },
    "PostProcessor": {"num_classes": 3, "num_top_queries": 50},
}
